use_frameworks!

platform :ios, '9.0'

target 'MTMWPhotoBrowser_Example' do
  pod 'MTMWPhotoBrowser', :path => '../'

  target 'MTMWPhotoBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
